version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_DB=linna
      - POSTGRES_PASSWORD=123456
    volumes:
      - data:/Users/lianghongma/Works/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "18080:8080"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "linna"]
      interval: 3s
      timeout: 3s
      retries: 5
volumes:
  data: