endpoint: 
  id: "linna-1"
  name: "linna"
  
log:
  level: "DEBUG"

data_dir: "./data"

runtime: 
  path: "./data/modules"
  env:
    - "ddd=ddddd"

metrics: 
  prometheus_port: 8801

db: 
  address:
     - "postgres:123456@localhost:5432/linna"
